USE [master]
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2
GO

ALTER LOGIN sa ENABLE ;
GO
ALTER LOGIN sa WITH PASSWORD = 'MSAzure#123' ;
GO

USE [master]
GO

/****** Object:  Database [WWI]    Script Date: 07-07-2020 14:16:13 ******/
CREATE DATABASE [WWI]
GO

ALTER DATABASE [WWI] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WWI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WWI] SET ANSI_NULL_DEFAULT OFF 
GO


ALTER DATABASE [WWI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WWI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WWI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WWI] SET ARITHABORT OFF 
GO

ALTER DATABASE [WWI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WWI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WWI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WWI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WWI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WWI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WWI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WWI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WWI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WWI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WWI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WWI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WWI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WWI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WWI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WWI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WWI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WWI] SET RECOVERY FULL 
GO

ALTER DATABASE [WWI] SET  MULTI_USER 
GO

ALTER DATABASE [WWI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WWI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WWI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WWI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WWI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WWI] SET QUERY_STORE = OFF
GO

USE [WWI]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [WWI] SET  READ_WRITE 
GO
